[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.5"
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio-native-tls"]}
tokio = { version = "1.47.1", features = ["full"] }
tracing-subscriber = "0.3.20"
